### ISSUE TITLE
Just a Word of Appreciation!

### ISSUE THREAD

**Issue by loneicewolf** [stong/infosec-resources#6]
Hello!
I just browsed trough some repos in infosec; (I am myself taking a break from the topic, so I am just browsing), And found this repo!

What I wanted to say however, was that This repo is both  easy to read(well written & well structured)* and very informative!; Thanks for compiling this list, and have a great weekend on you!

Note; I apologize for making a issue when it's not a 'issue', it's more of a 'thank you' (as I, kind of always do when discovering very good repos(repos like this one)) 

<sub>this 'issue' can be closed! Wishes from Sweden!</sub>

**Comment by loneicewolf** [comment]
Nice to see SageMath here as well! 
![image](https://github.com/stong/infosec-resources/assets/68499986/d65dc12b-59a1-4dc8-90f7-6478c8377702)

**Comment by stong** [comment]
No worries, your kind words mean a lot to me. Feel free to also make pull requests with any suggestions as well!

Have a great weekend,

Stephen

**Comment by loneicewolf** [comment]
Will do! I actually forked it to *do just that* ^_^ Do point out to me if anything is off in the (soon coming) fork! :)

**Comment by loneicewolf** [comment]
Now done with the pull request; Check it only when you have time, 

Regards!
Ill close this issue :)
